carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('check_cart_status/', views.check_cart_status, name='check_cart_status'),
]

selvarsu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.store,name='store'),
    path('category/<slug:category_slug>/',views.store,name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/',views.product_detail,name='product_detail'),
    path('search/',views.search,name='search'),
    path('submit_review/<int:product_id>/',views.submit_review,name='submit_review'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    user = models.ForeignKey('accounts.Account', on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    
    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return self.product.product_name

store/models.py
from django.db import models
from Category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg
from django.db.models import Count



# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name
    
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


    

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)
    
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.Account', on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from .models import Cart, CartItem
from store.models import Product, Variation
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variation = []
    
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except:
                pass
    
    if request.user.is_authenticated:
        # For authenticated users
        cart_items = CartItem.objects.filter(product=product, user=request.user)
        
        if cart_items.exists():
            # Check if exact same variations exist
            ex_var_list = []
            id_list = []
            
            for item in cart_items:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id_list.append(item.id)
            
            # If same variations found, increment quantity
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id, user=request.user)
                item.quantity += 1
                item.save()
            else:
                # Different variations, create new cart item
                item = CartItem.objects.create(
                    product=product, 
                    quantity=1, 
                    user=request.user
                )
                if len(product_variation) > 0:
                    item.variations.add(*product_variation)
                item.save()
        else:
            # First time adding this product
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=request.user,
            )
            if len(product_variation) > 0:
                cart_item.variations.add(*product_variation)
            cart_item.save()
    else:
        # For anonymous users
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        cart_items = CartItem.objects.filter(product=product, cart=cart)
        
        if cart_items.exists():
            # Check if exact same variations exist
            ex_var_list = []
            id_list = []
            
            for item in cart_items:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id_list.append(item.id)
            
            # If same variations found, increment quantity
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id, cart=cart)
                item.quantity += 1
                item.save()
            else:
                # Different variations, create new cart item
                item = CartItem.objects.create(
                    product=product, 
                    quantity=1, 
                    cart=cart
                )
                if len(product_variation) > 0:
                    item.variations.add(*product_variation)
                item.save()
        else:
            # First time adding this product
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.add(*product_variation)
            cart_item.save()
    
    return redirect('cart')

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except (Cart.DoesNotExist, CartItem.DoesNotExist):
        pass
    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        cart_item.delete()
    except (Cart.DoesNotExist, CartItem.DoesNotExist):
        pass
    return redirect('cart')

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        city = request.POST.get('city')
        state = request.POST.get('state')
        country = request.POST.get('country')
        zip_code = request.POST.get('zip_code')
        order_note = request.POST.get('order_note')
        
        messages.success(request, 'Order placed successfully!')
        return redirect('store')
    
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/checkout.html', context)


def check_cart_status(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        color = request.POST.get('color')
        size = request.POST.get('size')
        
        try:
            product = Product.objects.get(id=product_id)
            selected_variations = []
            
            if color:
                color_variation = Variation.objects.get(product=product, variation_category__iexact='color', variation_value__iexact=color)
                selected_variations.append(color_variation)
            
            if size:
                size_variation = Variation.objects.get(product=product, variation_category__iexact='size', variation_value__iexact=size)
                selected_variations.append(size_variation)
            
            in_cart = False
            
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, product=product)
            else:
                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                    cart_items = CartItem.objects.filter(cart=cart, product=product)
                except:
                    cart_items = []
            
            for cart_item in cart_items:
                existing_variations = list(cart_item.variations.all())
                if set(selected_variations) == set(existing_variations):
                    in_cart = True
                    break
            
            return JsonResponse({'in_cart': in_cart})
        
        except:
            return JsonResponse({'in_cart': False})
    
    return JsonResponse({'in_cart': False})

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
<h2 class="text-center">Your Shopping Cart is Empty</h2>
<br>
<div class="text-center">
    <a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
	{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
					{% if cart_item.variations.all %}
						{% for item in cart_item.variations.all %}
							{{ item.variation_category|capfirst }}: {{ item.variation_value|capfirst }} <br>
						{% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control" value="{{ cart_item.quantity }}" readonly>
							<div class="input-group-append">
								<form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.variations.all %}
										<input type="hidden" name="{{ item.variation_category|lower }}" value="{{ item.variation_value }}">
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i></button>
								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">Rs. {{ cart_item.sub_total }}</var> 
			<small class="text-muted"> Rs. {{ cart_item.product.price }} each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to remove this item?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}


</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">Rs. {{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> Rs. {{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>Rs. {{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

	</aside> <!-- col.// -->
</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .// -->
</section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<div class="card">
    <div class="row no-gutters">
        <aside class="col-md-6">
            <article class="gallery-wrap"> 
                <div class="img-big-wrap mainImage">
                    <center>
                        <img src="{{ single_product.images.url }}" id="mainImage" alt="{{ single_product.product_name }}">
                    </center>
                </div>
            </article> 

            <ul class="thumb">
                <li>
                    <a href="{{ single_product.images.url }}" onclick="changeImage(this.href); return false;">
                        <img src="{{ single_product.images.url }}" alt="Product Image">
                    </a>
                </li>
                {% for gallery_item in product_gallery %}
                <li>
                    <a href="{{ gallery_item.image.url }}" onclick="changeImage(this.href); return false;">
                        <img src="{{ gallery_item.image.url }}" alt="Product Image">
                    </a>
                </li>
                {% endfor %}
            </ul>
        </aside>
        
        <main class="col-md-6 border-left">
            <form action="{% url 'add_cart' single_product.id %}" method="POST" id="cart-form">
                {% csrf_token %}
                <article class="content-body">
                    <h2 class="title">{{ single_product.product_name }}</h2>
                    <div class="mb-3"> 
                        <var class="price h4">Rs. {{ single_product.price }}</var> 
                    </div> 
                    <p>{{ single_product.description }}</p>
                    <hr>
                    
                    {% if single_product.variation_set.colors %}
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Choose Color</h6>
                            <select name="color" class="form-control variation-select" required>
                                <option value="" disabled selected>Select Color</option>
                                {% for i in single_product.variation_set.colors %}
                                <option value="{{ i.variation_value|lower }}">{{ i.variation_value|capfirst }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %}
                    
                    {% if single_product.variation_set.sizes %}
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Select Size</h6>
                            <select name="size" class="form-control variation-select" required>
                                <option value="" disabled selected>Select Size</option>
                                {% for i in single_product.variation_set.sizes %}
                                <option value="{{ i.variation_value|lower }}">{{ i.variation_value|capfirst }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %}
                    
                    <hr>
                    {% if single_product.stock <= 0 %}
                        <button class="btn btn-secondary text-disabled" disabled>Out of Stock</button>
                    {% else %}
                        <div id="cart-buttons">
                            <button type="submit" class="btn btn-primary" id="add-cart-btn"> 
                                <span class="text">Add to cart</span> 
                                <i class="fas fa-shopping-cart"></i>
                            </button>
                        </div>
                    {% endif %}
                </article>
            </form>
        </main>
    </div>
</div>

</div>
</section>

<script>
function changeImage(imageUrl) {
    document.getElementById('mainImage').src = imageUrl;
}

// jQuery fallback
$(document).ready(function(){
    $('ul.thumb a').click(function(e) {
        e.preventDefault();
        var imageUrl = $(this).attr('href');
        $('#mainImage').attr('src', imageUrl);
    });
});
</script>
{% endblock %}

<script>
$(document).ready(function(){
    $('.variation-select').change(function(){
        checkCartStatus();
    });
    
    function checkCartStatus() {
        var color = $('select[name="color"]').val();
        var size = $('select[name="size"]').val();
        
        // Only check if both variations are selected
        if (color && size) {
            $.ajax({
                url: '{% url "check_cart_status" %}',
                type: 'POST',
                data: {
                    'product_id': {{ single_product.id }},
                    'color': color,
                    'size': size,
                    'csrfmiddlewaretoken': $('[name=csrfmiddlewaretoken]').val()
                },
                success: function(response) {
                    if (response.in_cart) {
                        $('#cart-buttons').html(`
                            <a href="{% url 'cart' %}" class="btn btn-success"> 
                                <span class="text">Added to Cart</span> 
                                <i class="fas fa-check"></i>
                            </a>
                            <a href="{% url 'cart' %}" class="btn btn-outline-primary"> 
                                <span class="text">View Cart</span> 
                                <i class="fas fa-eye"></i>
                            </a>
                        `);
                    } else {
                        $('#cart-buttons').html(`
                            <button type="submit" class="btn btn-primary" id="add-cart-btn"> 
                                <span class="text">Add to cart</span> 
                                <i class="fas fa-shopping-cart"></i>
                            </button>
                        `);
                    }
                }
            });
        }
    }
});
</script>

templates/store/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Search Results</h2>
	{% if keyword %}
	<p>{{ product_count }} result{{ product_count|pluralize }} found for "<strong>{{ keyword }}</strong>"</p>
	{% endif %}
	{% else %}
	<h2 class="title-page">Our Store</h2>
	{% endif %}
</div> <!-- container //  -->
</section> <!-- section-header.// -->

<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">
				
				<ul class="list-menu">
					<li><a href="{%url 'store' %}">All Products</li>
					{% for category in links %}
				<li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
				{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">Rs.0</option>
						<option value="50">Rs.50</option>
						<option value="100">Rs.100</option>
						<option value="150">Rs.150</option>
						<option value="200">Rs.200</option>
						<option value="500">$500</option>
						<option value="1000">Rs.1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">Rs.50</option>
						<option value="100">Rs.100</option>
						<option value="150">Rs.150</option>
						<option value="200">Rs.200</option>
						<option value="500">Rs.500</option>
						<option value="1000">Rs.1000</option>
						<option value="2000">Rs.2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">
	<div class="row">
		{% if products %}
			{% for product in products %}
			<div class="col-md-4">
				<figure class="card card-product-grid">
					<div class="img-wrap"> 
						<a href="{{ product.get_url }}">
							<img src="{{ product.images.url }}" alt="{{ product.product_name }}">
						</a>
					</div>
					<figcaption class="info-wrap">
						<div class="fix-height">
							<a href="{{ product.get_url }}" class="title">{{ product.product_name }}</a>
							<div class="price-wrap mt-2">
								<span class="price">Rs. {{ product.price }}</span>
							</div>
						</div>
						<a href="{{ product.get_url }}" class="btn btn-block btn-primary">View Details</a>
					</figcaption>
				</figure>
			</div>
			{% endfor %}
		{% else %}
			<div class="col-12">
				<div class="text-center py-5">
					{% if 'search' in request.path %}
						<h3>No products found</h3>
						<p>Try searching with different keywords</p>
					{% else %}
						<h3>No products available</h3>
					{% endif %}
				</div>
			</div>
		{% endif %}
	</div>
	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ======


{% endblock %}